-- ******************************************************************
-- Names: Ricky (Jatinder) Badyal, Wen Jiang
-- ID: 020028098,119838167
-- Date: 04/08/2019
-- Purpose: Submission for Group Assignment 2 for DBS301SAB
-- Description: This file includes several SQL scripts that
--              demonstrate the ability to retrieve data from a
--              relational database.
-- ***************************************************************


-- CREATION SCRIPT FOR TABLES:


    CREATE TABLE CLIENTS(
    CLIENT_ID NUMBER(6,0)  PRIMARY KEY,
    LAST_NAME VARCHAR2 (25),
    FIRST_NAME VARCHAR2(20),
    PHONE_NUMBER VARCHAR(20),
    EMAIL VARCHAR(20),
    STATUS VARCHAR(20),
    OWNERSHIP_PRECCENT VARCHAR2(25)
    );
   
   CREATE TABLE WLOCATIONS (
    LOCATION_ID NUMBER(6,0) PRIMARY KEY,
    COUNTRY VARCHAR2(35),
    STATE_PROVINCE VARCHAR2(25),
    CITY VARCHAR(30),
    POSTAL_CODE VARCHAR2(12),
    STREET_ADDRESS VARCHAR2(40)
    );
    
   
    
    CREATE TABLE AGENCY(
    AGENCY_ID NUMBER(6,0) PRIMARY KEY,
    AGENCY_NAME VARCHAR2(25)
    );
    
   
    
    CREATE TABLE OUTLET (
    OUTLET_ID NUMBER(6,0) PRIMARY KEY,
    OUTLET_NAME VARCHAR2(25),
    PHONE_NUMBER VARCHAR2(20)
    );
    
    
    CREATE TABLE REFERRALS (
    REFERRAL_ID NUMBER(6,0) PRIMARY KEY,
    REFERRAL_NAME VARCHAR(25)
    );
    

    CREATE TABLE AREA(
    AREA_ID NUMBER(6,0) PRIMARY KEY,
    AREA_NAME VARCHAR2(25),
    AREA_COMMENTS VARCHAR2(40)
    );
    
-----------------------------------

    CREATE TABLE PROPERTY(
    PROPERTY_ID NUMBER(6,0) PRIMARY KEY,
    CLIENT_ID NUMBER(6,0),
    AGENCY_ID NUMBER(6,0),
    LOCATION_ID NUMBER(6,0),
    AREA_ID NUMBER(6,0),
    NUMBER_OF_BEDROOMS NUMBER(1),
    NUMBER_OF_BATHROOMS NUMBER(1),
    SQUARE_FEET NUMBER(2,3),
    PROPERTY_TYPE VARCHAR2(25),
    MAINTAINCE_FEE NUMBER(8,2),
    CONSTRAINT CLIENT_ID_FK FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID),
    CONSTRAINT AGENCY_ID_FK FOREIGN KEY (AGENCY_ID) REFERENCES AGENCY(AGENCY_ID),
    CONSTRAINT LOCATION_ID_FK FOREIGN KEY (LOCATION_ID) REFERENCES WLOCATIONS(LOCATION_ID),
    CONSTRAINT AREA_ID_FK FOREIGN KEY(AREA_ID) REFERENCES AREA(AREA_ID)
    );
  

    CREATE TABLE SOLDPROPERTY(
    SALES_ID NUMBER(6,0) PRIMARY KEY,
    CLIENT_ID NUMBER(6,0),
    REFERRAL_ID NUMBER(6,0),
    SELLING_PRICE NUMBER(8,0),
    SELLING_DATE DATE,
    CONSTRAINT PROP_CLIENT_ID_FK FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID),
    CONSTRAINT PROP_REFERRAL_ID_FK FOREIGN KEY (REFERRAL_ID) REFERENCES REFERRALS(REFERRAL_ID)
    );
    
    DROP TABLE ADVERTISMENTS;
    CREATE TABLE ADVERTISMENTS(
    ADVERTISMENT_ID NUMBER(6,0) PRIMARY KEY,
    OUTLET_ID NUMBER(6,0),
    COST NUMBER(8,0),
    DATE_POSTED DATE,
    CONSTRAINT ADV_OUTLET_ID_FK FOREIGN KEY(OUTLET_ID) REFERENCES OUTLET(OUTLET_ID)
    );
    
    
    CREATE TABLE SCHOOLS(
    SCHOOL_ID NUMBER(6,0) PRIMARY KEY,
    AREA_ID NUMBER(6,0),
    SCHOOL_NAME VARCHAR2(25),
    SCHOOL_TYPE VARCHAR2(25),
    CONSTRAINT SCH_AREA_ID_FK FOREIGN KEY (AREA_ID) REFERENCES AREA(AREA_ID)
    );
    